spring.application.name=student-management
# 1. Database URL and Credentials
spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=1234

# 2. Hibernate Magic: "update" means Spring will automatically create/update tables for you!
spring.jpa.hibernate.ddl-auto=update

# 3. Show the actual SQL queries in the IntelliJ console (Great for interviews/debugging)
spring.jpa.show-sql=true
